# Generated by Django 4.1.7 on 2023-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(null=True, verbose_name='Quantidade em Estoque'),
        ),
    ]
